drop table if exists MG_USER;
create table if not exists MG_USER
(
  ID bigint not null primary key,
  EMAIL varchar(256) null,
  FIRST_NAME varchar(256) null,
  LAST_NAME varchar(256) null,
  MOBILE_PHONE varchar(256) null,
  USERNAME varchar(512) null,
  AVATAR_URL varchar(512) null,
  DEF_LANG char(2) null,
  DEF_COUNTRY char(2) null,
  TIMEZONE bigint null,
  RECEIVE_NOTIF tinyint default 0 null,
  REG_CONFIRMED tinyint default 0 null,
  WALLET varchar(256) null,
  TELEGRAM varchar(256) null,
  GENDER tinyint null,
  BDAY date null,
  COMPANY varchar(256) null,
  POSITION varchar(256) null,
  AGE smallint(6) null,
  COMPANY_PAGE varchar(256) null,
  BUSINESS_TYPE varchar(256) null,
  SHOW_WIZARD tinyint(1) default 1 null,
  DEF_CURRENCY varchar(100) null,
  TERMS_CONFIRMED tinyint(1) default 0 null,
  PRIVACY_POLICY_CONFIRMED tinyint(1) default 0 null,
  WHATSAPP varchar(256) null,
  VIBER varchar(256) null,
  DEF_CITY varchar(256) null,
  EDUCATION enum('HIGHER', 'SECONDARY', 'WITHOUT') null,
  INCOME enum('LESS_THAN_1000', '1000_3000', 'MORE_THAN_3000') null,
  INTERESTS varchar(1000) null,
  EMAIL_ENABLED tinyint(1) default 1 null,
  BUDGET_FROM int null,
  BUDGET_TO int null,
  SHOW_SURVEY tinyint(1) default 0 null,
  WIZARD_STEP int default 1 null,
  IS_ADULT tinyint(1) default 0 null,
  MARGIN double null,
  BALANCE double default 0 null,
  GEOTAG varchar(512) null,
  ACCOUNT_TAG varchar(256) null,
  REG_IP varchar(256) null,
  REG_COUNTRY varchar(256) null,
  HIVE_RATE int default 20 null,
  FORM_TOKENS tinyint(1) default 1 null,
  REG_PROJECT varchar(256) null
);
delete from ACL_GROUP;
insert into ACL_GROUP(ID,NAME,DESCRIPTION) values(14,'Advertiser','Advertiser');
