CREATE TABLE IF NOT EXISTS ADH_NOTIFICATION (
  ID              BIGINT NOT NULL PRIMARY KEY ,
  TO_ID           BIGINT NOT NULL,
  TITLE           VARCHAR(512),
  DESCRIPTION     TEXT,
  STATUS          VARCHAR(256),
  ADDED           DATETIME DEFAULT NULL,
  SYSTEM_FIELD          VARCHAR(256)
);

CREATE INDEX IF NOT EXISTS ADH_NOTIFICATION_TO_ID_IDX ON ADH_NOTIFICATION (TO_ID);
CREATE INDEX IF NOT EXISTS ADH_NOTIFICATION_STATUS_IDX ON ADH_NOTIFICATION (STATUS);

-- notifications
DELETE FROM ADH_NOTIFICATION;
